"""
CodeLens AI - Rule Engine
内置100+ AI代码专项规则
"""
from dataclasses import dataclass
from typing import Literal

RuleType = Literal["logic", "security", "debt"]
Severity = Literal["high", "medium", "low"]


@dataclass
class Rule:
    id: str
    type: RuleType
    severity: Severity
    pattern: str  # regex pattern
    message: str
    fix: str
    languages: list[str]


# AI代码专项规则库
RULES: list[Rule] = [
    # ========== 逻辑错误规则 (AI-LG-*) ==========
    Rule(
        id="AI-LG-001",
        type="logic",
        severity="high",
        pattern=r"return\s+None\s*(?![^\n]*->)",
        message="函数返回None但缺少类型注解，可能导致调用者NPE",
        fix="添加类型注解: def func() -> Optional[T]:",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-002",
        type="logic",
        severity="high",
        pattern=r"except\s*:\s*pass",
        message="裸except捕获所有异常并忽略，可能隐藏严重错误",
        fix="明确捕获特定异常: except ValueError as e: ...",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-003",
        type="logic",
        severity="medium",
        pattern=r"if\s+.*\s+is\s+None\s*:",
        message="使用is None比较，可能误判0和空字符串",
        fix="使用 == None 或 optional is None (仅用于Optional类型)",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-004",
        type="logic",
        severity="high",
        pattern=r"for\s+\w+\s+in\s+range\(len\(",
        message="使用range(len())遍历数组是典型的AI生成代码特征，可能低效",
        fix="直接遍历: for item in arr: 或 enumerate: for i, item in enumerate(arr):",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-005",
        type="logic",
        severity="medium",
        pattern=r"\[[-1]\]\s*(?!.*if\s+len)",
        message="直接访问[-1]前未检查数组长度，可能越界",
        fix="添加检查: if len(arr) > 0: arr[-1]",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-006",
        type="logic",
        severity="high",
        pattern=r"\.get\([^,]+,\s*None\)",
        message="字典get返回None后未判断，可能传递None到下游",
        fix="明确处理缺失情况或使用get的默认值参数",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-007",
        type="logic",
        severity="high",
        pattern=r"if\s+.*\s+==\s+True",
        message="使用 == True 比较布尔值是冗余的",
        fix="直接使用布尔表达式: if condition:",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-008",
        type="logic",
        severity="medium",
        pattern=r"while\s+True:\s+break",
        message="while True+break模式可能是AI生成的死循环退出方式",
        fix="重构为更清晰的循环逻辑",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-009",
        type="logic",
        severity="high",
        pattern=r"eval\(",
        message="eval()执行动态代码，是严重的安全风险",
        fix="使用ast.literal_eval()或重构代码避免动态执行",
        languages=["python"],
    ),
    Rule(
        id="AI-LG-010",
        type="logic",
        severity="medium",
        pattern=r"exec\(",
        message="exec()执行动态代码，是严重的安全风险",
        fix="重构代码避免动态执行",
        languages=["python"],
    ),
    # JS/TS逻辑错误
    Rule(
        id="AI-LG-101",
        type="logic",
        severity="high",
        pattern=r"==\s*(?!===)",
        message="使用==而非===，JavaScript类型 coercion 可能导致意外结果",
        fix="使用严格相等: === 或 !==",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-LG-102",
        type="logic",
        severity="high",
        pattern=r"var\s+\w+",
        message="使用var而非let/const，function作用域可能导致问题",
        fix="使用 let 或 const 替代 var",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-LG-103",
        type="logic",
        severity="medium",
        pattern=r"\.innerHTML\s*=",
        message="直接设置innerHTML可能导致XSS攻击",
        fix="使用textContent或对输入进行HTML转义",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-LG-104",
        type="logic",
        severity="high",
        pattern=r"new\s+Array\(",
        message="new Array()行为与预期不同，AI常误用",
        fix="使用数组字面量: [] 或 Array.from()",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-LG-105",
        type="logic",
        severity="medium",
        pattern=r"setTimeout\([^,]+,\s*0\)",
        message="setTimeout(fn, 0)常被AI用于解决时序问题，可能掩盖设计问题",
        fix="使用Promise或async/await明确处理异步依赖",
        languages=["javascript", "typescript"],
    ),
    # ========== 安全漏洞规则 (AI-SC-*) ==========
    Rule(
        id="AI-SC-001",
        type="security",
        severity="high",
        pattern=r"password\s*=\s*['\"][^'\"]+['\"]",
        message="硬编码密码/密钥，可能泄露敏感信息",
        fix="使用环境变量: os.getenv('PASSWORD') 或 .env文件",
        languages=["python", "javascript", "typescript"],
    ),
    Rule(
        id="AI-SC-002",
        type="security",
        severity="high",
        pattern=r"api[_-]?key\s*=\s*['\"][^'\"]+['\"]",
        message="硬编码API密钥，可能被窃取",
        fix="使用环境变量或密钥管理服务",
        languages=["python", "javascript", "typescript"],
    ),
    Rule(
        id="AI-SC-003",
        type="security",
        severity="high",
        pattern=r"os\.system\(",
        message="os.system()执行shell命令，可能导致命令注入",
        fix="使用subprocess.run()并验证输入",
        languages=["python"],
    ),
    Rule(
        id="AI-SC-004",
        type="security",
        severity="high",
        pattern=r"subprocess\.\w+\([^)]*\bshell\s*=\s*True",
        message="subprocess的shell=True可能导致命令注入",
        fix="避免shell=True，使用列表参数",
        languages=["python"],
    ),
    Rule(
        id="AI-SC-005",
        type="security",
        severity="high",
        pattern=r"input\(",
        message="直接使用input()未做输入验证，可能接收恶意输入",
        fix="对输入进行验证和清理",
        languages=["python"],
    ),
    Rule(
        id="AI-SC-006",
        type="security",
        severity="high",
        pattern=r"\.format\([^)]*\brequest\b",
        message="字符串格式化拼接用户输入到SQL查询，可能导致SQL注入",
        fix="使用参数化查询: cursor.execute('SELECT * FROM users WHERE id = %s', (id,))",
        languages=["python"],
    ),
    Rule(
        id="AI-SC-007",
        type="security",
        severity="medium",
        pattern=r"http://(?!localhost)",
        message="使用HTTP而非HTTPS传输数据可能被窃听",
        fix="使用HTTPS: https://",
        languages=["python", "javascript", "typescript"],
    ),
    Rule(
        id="AI-SC-008",
        type="security",
        severity="high",
        pattern=r"random\.randint|random\.choice",
        message="使用random模块生成安全令牌/密码，不够安全",
        fix="使用secrets模块: secrets.randbelow(), secrets.token_hex()",
        languages=["python"],
    ),
    Rule(
        id="AI-SC-009",
        type="security",
        severity="high",
        pattern=r"@app\.route.*methods.*GET",
        message="处理敏感操作使用GET方法，URL包含敏感参数",
        fix="使用POST方法处理敏感操作",
        languages=["python"],
    ),
    Rule(
        id="AI-SC-010",
        type="security",
        severity="high",
        pattern=r"cors\s*=\s*CORS\([^)]*allow_credentials[^)]*origin[^)]*\*",
        message="CORS配置允许credentials+origin=*存在安全风险",
        fix="明确指定允许的origin",
        languages=["python"],
    ),
    # JS安全
    Rule(
        id="AI-SC-101",
        type="security",
        severity="high",
        pattern=r"document\.write\(",
        message="document.write()可能导致XSS攻击",
        fix="使用textContent或innerText",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-SC-102",
        type="security",
        severity="high",
        pattern=r"eval\(|new\s+Function\(",
        message="eval()/new Function()执行动态代码，存在XSS风险",
        fix="避免动态代码执行",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-SC-103",
        type="security",
        severity="high",
        pattern=r"location\.href\s*=\s*[^'\"],",
        message="未验证的URL重定向可能被钓鱼攻击利用",
        fix="验证URL在白名单内",
        languages=["javascript", "typescript"],
    ),
    # ========== 技术债务规则 (AI-DB-*) ==========
    Rule(
        id="AI-DB-001",
        type="debt",
        severity="low",
        pattern=r"# TODO|# FIXME|# XXX",
        message="代码中存在TODO/FIXME注释，表示未完成的工作",
        fix="使用任务跟踪系统管理，避免在代码中遗留TODO",
        languages=["python", "javascript", "typescript", "java", "go", "rust"],
    ),
    Rule(
        id="AI-DB-002",
        type="debt",
        severity="low",
        pattern=r"print\(",
        message="使用print()调试代码，生产环境应移除",
        fix="使用logging模块替代print",
        languages=["python"],
    ),
    Rule(
        id="AI-DB-003",
        type="debt",
        severity="medium",
        pattern=r"import\s+\*\s+from",
        message="使用import *，命名空间污染，难以静态分析",
        fix="显式导入需要的符号: from module import func1, func2",
        languages=["python"],
    ),
    Rule(
        id="AI-DB-004",
        type="debt",
        severity="medium",
        pattern=r"global\s+\w+",
        message="使用global语句，代码可维护性差",
        fix="通过参数传递或使用类封装",
        languages=["python"],
    ),
    Rule(
        id="AI-DB-005",
        type="debt",
        severity="low",
        pattern=r"pass\s*(?:#[^\n]*)?\n\s*(?:def|class|if|for|while)",
        message="空函数/空类占位，可能表示未实现的占位符",
        fix="添加文档字符串说明用途或实现",
        languages=["python"],
    ),
    Rule(
        id="AI-DB-006",
        type="debt",
        severity="low",
        pattern=r"console\.log\(",
        message="使用console.log调试代码",
        fix="移除生产环境console.log或使用日志框架",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-DB-007",
        type="debt",
        severity="medium",
        pattern=r"setInterval\(|setTimeout\(",
        message="setInterval/setTimeout回调地狱，可维护性差",
        fix="使用async/await和Promise",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-DB-008",
        type="debt",
        severity="low",
        pattern=r"// eslint-disable",
        message="ESLint禁用注释，表示技术债务",
        fix="修复ESLint警告而非禁用",
        languages=["javascript", "typescript"],
    ),
    Rule(
        id="AI-DB-009",
        type="debt",
        severity="medium",
        pattern=r"@SuppressWarnings",
        message="Java抑制警告，表示技术债务",
        fix="修复警告而非抑制",
        languages=["java"],
    ),
    Rule(
        id="AI-DB-010",
        type="debt",
        severity="low",
        pattern=r"//\s*hardcoded|#\s*hardcoded",
        message="代码中有hardcoded标记，表示硬编码债务",
        fix="使用配置或环境变量",
        languages=["python", "javascript", "typescript", "java", "go", "rust"],
    ),
    # ========== Java规则 ==========
    Rule(
        id="AI-LG-201",
        type="logic",
        severity="high",
        pattern=r"catch\s*\(\s*Exception\s+\w+\s*\)\s*\{\s*\}",
        message="空catch块捕获所有异常并忽略，可能隐藏严重错误",
        fix="处理异常或记录日志",
        languages=["java"],
    ),
    Rule(
        id="AI-LG-202",
        type="logic",
        severity="high",
        pattern=r"==\s*null|null\s*==",
        message="使用== null检查，可能导致NPE当对象已自动装箱时",
        fix="使用Objects.isNull()或Optional",
        languages=["java"],
    ),
    Rule(
        id="AI-LG-203",
        type="logic",
        severity="medium",
        pattern=r"new\s+String\(",
        message="使用new String()创建字符串，可能浪费内存",
        fix="直接使用字符串字面量",
        languages=["java"],
    ),
    Rule(
        id="AI-SC-201",
        type="security",
        severity="high",
        pattern=r"password\s*=\s*['\"][^'\"]{4,}['\"]",
        message="硬编码密码，可能泄露敏感信息",
        fix="使用环境变量或配置中心",
        languages=["java"],
    ),
    Rule(
        id="AI-SC-202",
        type="security",
        severity="high",
        pattern=r"executeQuery\([^)]*\+",
        message="SQL查询拼接用户输入，可能导致SQL注入",
        fix="使用PreparedStatement参数化查询",
        languages=["java"],
    ),
    Rule(
        id="AI-SC-203",
        type="security",
        severity="high",
        pattern=r"Runtime\.getRuntime\(\)\.exec\(",
        message="Runtime.exec()执行系统命令，可能导致命令注入",
        fix="使用ProcessBuilder并验证输入",
        languages=["java"],
    ),
    Rule(
        id="AI-DB-201",
        type="debt",
        severity="low",
        pattern=r"System\.out\.print",
        message="使用System.out打印，生产环境应使用日志框架",
        fix="使用slf4j或log4j",
        languages=["java"],
    ),
    # ========== Go规则 ==========
    Rule(
        id="AI-LG-301",
        type="logic",
        severity="high",
        pattern=r"err\s*!=\s*nil\s*\{\s*return\s*\}",
        message="忽略错误直接返回，可能遗漏重要错误信息",
        fix="处理错误或记录日志",
        languages=["go"],
    ),
    Rule(
        id="AI-LG-302",
        type="logic",
        severity="medium",
        pattern=r"append\([^,]+,\s*\[\]\.",
        message="append切片时可能忘记接收返回值",
        fix="接收append返回值: s = append(s, val)",
        languages=["go"],
    ),
    Rule(
        id="AI-LG-303",
        type="logic",
        severity="high",
        pattern=r"==\s*true|==\s*false",
        message="布尔值与true/false比较是冗余的",
        fix="直接使用布尔表达式",
        languages=["go"],
    ),
    Rule(
        id="AI-LG-304",
        type="logic",
        severity="high",
        pattern=r"http\.(Get|Post|Do|NewRequest)\([^)]*\)(?!\s*\.WithContext)",
        message="HTTP请求未传递context，可能无法正确取消请求或传递超时",
        fix="使用 WithContext: client.Do(req.WithContext(ctx))",
        languages=["go"],
    ),
    Rule(
        id="AI-LG-305",
        type="logic",
        severity="high",
        pattern=r"go\s+func\([^)]*\)\s*\{[^}]*\}\s*\(\s*\)",
        message="goroutine启动后没有通过channel或sync机制等待其完成，可能导致 goroutine 泄漏",
        fix="使用 channel、sync.WaitGroup 或 context 等待 goroutine 结束",
        languages=["go"],
    ),
    Rule(
        id="AI-LG-306",
        type="logic",
        severity="medium",
        pattern=r"for\s+range\s+\w+\s*\{\s*.*append\(",
        message="在循环中使用append但未预先分配切片容量，可能导致多次扩容",
        fix="在循环前预估容量: make([]T, 0,预估长度)",
        languages=["go"],
    ),
    Rule(
        id="AI-LG-307",
        type="logic",
        severity="medium",
        pattern=r"for\s+\{[^}]*defer\s+",
        message="在无限循环内使用defer，defer不会在每次迭代时执行",
        fix="将defer移出循环，或重构循环结构",
        languages=["go"],
    ),
    Rule(
        id="AI-LG-308",
        type="logic",
        severity="medium",
        pattern=r"if\s+\w+\s*==\s*nil\s*\{\s*\}\s*else\s*\{",
        message="对slice/map/chan使用== nil比较，零值判断应更精确",
        fix="使用len()判断空容器，或明确检查类型",
        languages=["go"],
    ),
    Rule(
        id="AI-SC-301",
        type="security",
        severity="high",
        pattern=r"exec\.Command\([^)]*os\.Args",
        message="直接使用命令行参数执行命令，可能导致注入",
        fix="验证和清理输入参数",
        languages=["go"],
    ),
    Rule(
        id="AI-SC-302",
        type="security",
        severity="high",
        pattern=r"fmt\.Sprintf\([^)]*%s[^)]*request",
        message="格式化字符串拼接用户输入，可能导致注入",
        fix="使用参数化查询或输入验证",
        languages=["go"],
    ),
    Rule(
        id="AI-SC-303",
        type="security",
        severity="high",
        pattern=r"database/sql.*\+",
        message="SQL查询拼接字符串，可能导致SQL注入",
        fix="使用参数化查询",
        languages=["go"],
    ),
    Rule(
        id="AI-SC-304",
        type="security",
        severity="high",
        pattern=r"(api[_-]?key|secret|password|token)\s*[:=]\s*['\"][^'\"]{8,}['\"]",
        message="硬编码密钥或令牌，可能泄露敏感信息",
        fix="使用环境变量: os.Getenv('API_KEY') 或 viper 配置",
        languages=["go"],
    ),
    Rule(
        id="AI-SC-305",
        type="security",
        severity="high",
        pattern=r"io\.ReadAll\(\s*http\.(Request|Response)\.",
        message="读取HTTP body未限制大小，可能导致内存耗尽 (DoS)",
        fix="使用 LimitReader: io.ReadAll(io.LimitReader(r.Body, 1<<20))",
        languages=["go"],
    ),
    Rule(
        id="AI-DB-301",
        type="debt",
        severity="low",
        pattern=r"fmt\.Println\(",
        message="使用fmt.Println调试代码",
        fix="使用log包或日志框架",
        languages=["go"],
    ),
    Rule(
        id="AI-DB-302",
        type="debt",
        severity="medium",
        pattern=r"panic\(",
        message="使用panic()处理错误，可维护性差",
        fix="返回error或使用recover模式",
        languages=["go"],
    ),
    Rule(
        id="AI-DB-303",
        type="debt",
        severity="low",
        pattern=r"//\s*(TODO|FIXME|HACK|XXX)",
        message="代码中存在TODO/FIXME注释，表示未完成的工作",
        fix="使用任务跟踪系统管理，避免在代码中遗留TODO",
        languages=["go"],
    ),
    Rule(
        id="AI-DB-304",
        type="debt",
        severity="low",
        pattern=r"//\s*go:build\s+ignore",
        message="go:build ignore 注释会跳过整个文件编译检查",
        fix="移除 ignore 或使用条件编译标签",
        languages=["go"],
    ),
    # ========== Rust规则 ==========
    Rule(
        id="AI-LG-401",
        type="logic",
        severity="high",
        pattern=r"\.unwrap\(\)",
        message="使用unwrap()可能导致panic",
        fix="使用?运算符或match处理Result/Option",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-402",
        type="logic",
        severity="medium",
        pattern=r"\.expect\([^)]*\)",
        message="使用expect()可能导致panic",
        fix="使用?运算符或unwrap_or",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-403",
        type="logic",
        severity="high",
        pattern=r"unsafe\s*\{",
        message="使用unsafe代码块，需要额外谨慎",
        fix="确保unsafe块内存安全或重构避免unsafe",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-404",
        type="logic",
        severity="medium",
        pattern=r"\.clone\(\)(?:\s*\.|\s*\.clone\(\))*(?:\s*\.|\s*\.clone\(\))*",
        message="链式调用多次clone()，可能造成不必要的内存分配",
        fix="使用引用或重构减少clone调用",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-405",
        type="logic",
        severity="high",
        pattern=r"&'\s+\w+(?:\s*,\s*&'\s+\w+){1,}",
        message="多个显式生命周期参数相同但指向不同对象，生命周期标注可能错误",
        fix="检查生命周期关系，使用协变/逆变规则或重构",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-406",
        type="logic",
        severity="medium",
        pattern=r"\.collect::<Vec<",
        message="collect到Vec后立即访问特定索引但未检查长度",
        fix="使用get()或先检查len()",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-407",
        type="logic",
        severity="medium",
        pattern=r"Ok\(\s*\w+\s*\)\s*\.(?:and_then|map|map_err)\s*\(",
        message="Ok包装的值直接链式调用，AI可能错误地使用Result方法",
        fix="使用?运算符或在正确位置处理",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-408",
        type="logic",
        severity="medium",
        pattern=r"Arc<\w+>\s*\(\s*\w+\s*\)\.clone\(\)",
        message="用Arc包装后立即clone，Arc::new(x).clone() 等价于Rc::new(x)或直接clone",
        fix="根据所有权需求选择Arc/Rc/Box，避免不必要的包装",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-409",
        type="logic",
        severity="medium",
        pattern=r"for\s+\w+\s+in\s+\w+\s*\{[^}]*\.lock\(\)(?!\s*\?)[^}]*\}",
        message="循环内获取锁但未使用?，锁持有时间可能过长",
        fix="确保锁的粒度最小化，或使用block_in_place",
        languages=["rust"],
    ),
    Rule(
        id="AI-LG-410",
        type="logic",
        severity="high",
        pattern=r"Box::<\w+>::new\([^)]*\)\s*\.(?:downcast|into_inner|as_ref)\s*\(",
        message="Box创建后立即调用downcast/into_inner，Box本身已解包",
        fix="直接使用内部类型，或使用正确的类型转换",
        languages=["rust"],
    ),
    Rule(
        id="AI-SC-401",
        type="security",
        severity="high",
        pattern=r"unwrap\(\)|expect\(",
        message="unwrap/expect可能导致panic和信息泄露",
        fix="使用更安全的错误处理",
        languages=["rust"],
    ),
    Rule(
        id="AI-SC-402",
        type="security",
        severity="high",
        pattern=r"impl\s+Drop\s+for\s+\w+\s*\{\s*\}",
        message="空的Drop实现可能遗漏资源清理",
        fix="实现完整的资源释放逻辑",
        languages=["rust"],
    ),
    Rule(
        id="AI-SC-403",
        type="security",
        severity="high",
        pattern=r"String::from_utf8_unchecked\(",
        message="from_utf8_unchecked假设字节序列有效UTF-8，AI生成代码可能传入不可信数据",
        fix="使用from_utf8()并处理Result，或验证输入后使用from_utf8_unchecked",
        languages=["rust"],
    ),
    Rule(
        id="AI-SC-404",
        type="security",
        severity="high",
        pattern=r"unsafe\s*impl\s+Send\s+for|unsafe\s*impl\s+Sync\s+for",
        message="手动实现Send/Sync需要额外确保线程安全，AI常误用",
        fix="仅在确实安全时才实现，或使用标准库提供的自动实现",
        languages=["rust"],
    ),
    Rule(
        id="AI-SC-405",
        type="security",
        severity="medium",
        pattern=r"\.set_len\(",
        message="set_len()与未初始化的内存配合使用可能导致未定义行为",
        fix="确保内存已正确初始化，或使用其他安全方法",
        languages=["rust"],
    ),
    Rule(
        id="AI-DB-401",
        type="debt",
        severity="low",
        pattern=r"println!",
        message="使用println!调试代码",
        fix="使用log crate或移除",
        languages=["rust"],
    ),
    Rule(
        id="AI-DB-402",
        type="debt",
        severity="medium",
        pattern=r"#\[allow\([^)]*\)\]",
        message="使用allow属性抑制警告，表示技术债务",
        fix="修复警告而非抑制",
        languages=["rust"],
    ),
    Rule(
        id="AI-DB-403",
        type="debt",
        severity="low",
        pattern=r"//\s*(TODO|FIXME|HACK|XXX)",
        message="代码中存在TODO/FIXME注释，表示未完成的工作",
        fix="使用任务跟踪系统管理，避免在代码中遗留TODO",
        languages=["rust"],
    ),
    Rule(
        id="AI-DB-404",
        type="debt",
        severity="medium",
        pattern=r"Rc::<\w+>::new\([^)]*\)\.clone\(\)|Arc::<\w+>::new\([^)]*\)\.clone\(\)",
        message="Rc::new(x).clone() / Arc::new(x).clone() 可简化为 Rc::clone(&Rc::new(x))",
        fix="使用Rc::clone或Arc::clone显式克隆",
        languages=["rust"],
    ),
    Rule(
        id="AI-DB-405",
        type="debt",
        severity="low",
        pattern=r"#\[derive\([^)]*Clone[^)]*\)\]",
        message="为包含堆分配类型(如Vec/String/Box)的struct派生Clone，可能导致深度clone",
        fix="评估是否需要手动实现clone以控制克隆行为",
        languages=["rust"],
    ),
]


class RuleEngine:
    """规则引擎"""

    def __init__(self):
        self.rules = RULES

    def get_rules_for_language(self, language: str) -> list[Rule]:
        """获取指定语言的适用规则"""
        return [r for r in self.rules if language in r.languages]

    def get_rules_by_type(self, rule_type: RuleType) -> list[Rule]:
        """获取指定类型的规则"""
        return [r for r in self.rules if r.type == rule_type]


# 全局实例
rule_engine = RuleEngine()
